INSERT INTO TBL_STUDENT(NAME, COURSE) VALUES ('Gabriela Amoroso','Medicina');
INSERT INTO TBL_STUDENT(NAME, COURSE) VALUES ('Enzo Roosch','ADS');
INSERT INTO TBL_STUDENT(NAME, COURSE) VALUES ('Pedro Bernardo','RH');